apiVersion: v1
kind: Service
metadata:
  name: app-bg
  namespace: bg
spec:
  type: NodePort
  selector:
    app: app-bg
    version: blue     # ðŸ‘ˆ initial traffic goes to GREEN
  ports:
  - name: http
    port: 80
    targetPort: 80
    nodePort: 30094
